
project_id = "cussrbqrhbmafhdrgaxo"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "localhost:3000", "localhost:3000/login"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
email_template_forgot_password_path = "emails/reset-password.html"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
port = 54324
function_timeout_seconds = 5
http_port = 54325
shell_path = "bash"

[functions.verify_jwt]
default_enabled = true

[functions.analyze-receipt]
verify_jwt = true

[functions.get-exchange-rates]
verify_jwt = false

[functions.get-metal-prices]
verify_jwt = false

[functions.get-stock-price]
verify_jwt = false

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth.sms]
enabled = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
