// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdcqeybnywfejrbdsvhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkY3FleWJueXdmZWpyYmRzdmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTQyMjIsImV4cCI6MjA1OTYzMDIyMn0.SVdufN0WPMQpeWCkt3ZmkCvHsfzxZHdyDIPGBbbY_m8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);