// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvdmtxoumqfpsejbdorr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2ZG10eG91bXFmcHNlamJkb3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTE5MzksImV4cCI6MjA2MDU4NzkzOX0.3cYvMBgULFklC_9WbRSRVigQRZyOWM1IFJD9kYqj-9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'uangkita_supabase_auth',
    flowType: 'pkce'
  }
});

// Tambahkan fungsi transfer
export const transferBetweenWallets = async (
  fromWalletId: string,
  toWalletId: string,
  amount: number,
  description: string
) => {
  try {
    const { data, error } = await supabase.rpc('transfer_between_wallets', {
      p_from_wallet_id: fromWalletId,
      p_to_wallet_id: toWalletId,
      p_amount: amount,
      p_description: description
    });

    if (error) throw error;
    return true;
  } catch (error) {
    console.error('Error transferring between wallets:', error);
    throw error;
  }
};
